services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/usr/src/app/apps/api
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accessibility_scanner_dev

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    volumes:
      - ./apps/worker:/usr/src/app/apps/worker
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accessibility_scanner_dev

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accessibility_scanner_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: 